#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# config.yaml

app:
  name: MyApp
  environment: production
  debug: false

api:
  base_url: https://api.example.com
  api_key: YOUR_API_KEY_HERE
  timeout: 30  # in seconds

logging:
  level: INFO
  file: logs/app.log
  rotation: daily

database:
  host: localhost
  port: 5432
  user: myuser
  password: mypassword
  name: mydatabase
