name: bs_trained_model_config_example

model:
  name: hfl/chinese-macbert-large
  labels:
    -1: NEGATIVE
    0: NEUTRAL
    1: POSITIVE
  path: exdir/path2modelcheckpoint/
  checkpoints:
    1: 

training:
  learning_rate:2e-5
  eval_strategy:epoch
  save_strategy:epoch
  save_total_limit:1
  auto_find_batch_size:True
  num_train_epochs:3
  weight_decacy:0.01
  logging_steps:300
  seed:42 
  data_seed:42
  save_safetensors:False
  per_device_eval_batch_size:8
  per_device_train_batch_size:8
  
data:
  path: exdir/df.parquet
  text: covariate
  label: target
